function [colour] = get_colour(i, cm)
%GET_COLOURS Summary of this function goes here
%   Detailed explanation goes here
    colours = {[cm, 0, 0], ...
               [cm, cm, 0], ...
               [cm, 0, cm], ...
               [0, cm, 0], ...
               [0, cm, cm], ...
               [0, 0, cm]};
    colour = colours{i};
end

