function [] = run_task_instructions(wh, white)


    Screen('TextStyle', wh, 1);
    Screen('TextSize', wh, 30);
    instructions = ...
        sprintf(['Now you have learned all you need\n',...
        'to learn to do the task!\n\n',...
        'During this task, the target will appear\n', ...
        'in either location.',...
        'You can still earn points based on the coloured\n'...
        'rings, and the arrow will still be helpful\n\n'...
        'Remember, the faster you respond, the more\n' ...
        'of the available points you will win!\n\n' ...
        'Press a key now to start.\n']);

    DrawFormattedText(wh, instructions, 'Center', 'Center', white, 115);
    Screen('Flip', wh);
    start_ts = KbWait;
    WaitSecs(0.5);

    
end