function [] = run_reward_instructions(wh, white)


    Screen('TextStyle', wh, 1);
    Screen('TextSize', wh, 30);
    instructions = ...
        sprintf(['Now you get to earn some cash rewards!\n'...
        'You will earn points each time you get\n'...
        'the task correct.\n\n'...
        'also, the faster you respond, the more\n' ...
        'of the available points you will win!\n\n' ...
        'Press a key now to see your next instruction.\n']);

    DrawFormattedText(wh, instructions, 'Center', 'Center', white, 115);
    Screen('Flip', wh);
    start_ts = KbWait;
    WaitSecs(0.5);
    
    Screen('TextStyle', wh, 1);
    Screen('TextSize', wh, 30);
    instructions = ...
        sprintf(['During this phase, the target will ALWAYS appear\n', ...
                 'within the coloured ring, and never within the grey ring\n', ...
                 'The colour provides probabilistic information\n', ...
                 'about how many points are available should the\n',...
                 'target appear there.\n\n',...
                 'Although it wont be completely 100 %% correct, it will\n'...
                 'be a good clue\n\n'...
                 'In a later stage of the task, the target will appear\n'...
                 'in either location, so you should still keep your eyes\n',...
                 'on the cross in the middle, as practice for later\n', ...
                 'You must get the task correct to earn the available\n',...
                 'points.\n\n']);
    
    DrawFormattedText(wh, instructions, 'Center', 'Center', white, 115);
    Screen('Flip', wh);
    start_ts = KbWait;
    WaitSecs(0.5);
    
    Screen('TextStyle', wh, 1);
    Screen('TextSize', wh, 30);
    instructions = ...
        sprintf(['At the end of each trial you will see two values. \n', ...
                 'The left value is the number of points you just earned, \n', ...
                 'the right value is the number of points you have\n', ...
                 'So if you saw \n',...
                 '50 -> 100 \n\n',...
                 'That would mean that you have just scored 50 points, \n'...
                 'which will be added to your existing total of 100 points\n\n'...
                 'Also, if you respond faster, you will get more of the \n'...
                 'available points.\n'...
                 'Press a key to see the first coloured ring\n\n']);
    DrawFormattedText(wh, instructions, 'Center', 'Center', white, 115);
    Screen('Flip', wh);
    start_ts = KbWait;
    WaitSecs(0.5);
    
    
end