function [] = run_reward_instructions(wh, white)


    Screen('TextStyle', wh, 1);
    Screen('TextSize', wh, 30);
    instructions = ...
        sprintf(['Now you get to earn some cash rewards!\n'...
        'You will earn points each time you get\n'...
        'the task correct.\n\n'...
        'also, the faster you respond, the more\n' ...
        'of the available points you will win!\n\n' ...
        'Press a key now to see your next instruction.\n']);

    DrawFormattedText(wh, instructions, 'Center', 'Center', white, 115);
    Screen('Flip', wh);
    start_ts = KbWait;
    WaitSecs(0.5);
    
    Screen('TextStyle', wh, 1);
    Screen('TextSize', wh, 30);
    instructions = ...
        sprintf(['The colour of the shape provides\n'...
                 'information about how many points are\n'...
                 'available should you get the task correct.\n\n'...
                 'Good luck!']);
    
    DrawFormattedText(wh, instructions, 'Center', 'Center', white, 115);
    Screen('Flip', wh);
    start_ts = KbWait;
    WaitSecs(0.5);
    
end