function [] = take_break_w_feedback(wh, white, task, t, total_t, n_t_between_breaks, reward_count) 

    Screen('TextStyle', wh, 1);
    Screen('TextSize', wh, 30); 
    instructions = ...
        sprintf(['Good work! You have earned %d points!\n\n', ...
        ' %d / %d blocks complete!\n\n', ...
        'Take a little break :) \n\n'...
        'Press %s for clockwise and %s for counterclockwise.\n'],...
        reward_count, t/n_t_between_breaks, total_t/n_t_between_breaks, ...
        KbName(task.responses(1)), KbName(task.responses(2)));
    DrawFormattedText(wh, instructions, 'Center', 'Center', white, 115);
    Screen('Flip', wh);
    start_ts = KbWait;

    WaitSecs(0.5);
end